import { Product } from "../types/Product";

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "AI Trading Bot",
    description: "Automated trading bot with machine learning. Includes advanced algorithms for market analysis and automated trading strategies.",
    price: 9.99,
    currency: "XRP",
    category: "Software",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=500&h=500&fit=crop",
    rating: 4.8,
    sales: 1200,
    seller: "rpVh7YjJTokEm5GSAVbSP6JSCVH1XKuDxN",
  },
  {
    id: "2",
    name: "Crypto Dashboard",
    description: "Real-time portfolio tracking dashboard with advanced analytics and customizable widgets.",
    price: 5.99,
    currency: "XRP",
    category: "Tools",
    image: "https://images.unsplash.com/photo-1551431009-381d36ac3a99?w=500&h=500&fit=crop",
    rating: 4.6,
    sales: 850,
    seller: "rpVh7YjJTokEm5GSAVbSP6JSCVH1XKuDxN",
  },
  {
    id: "3",
    name: "Smart Contract Templates",
    description: "Pre-audited XRPL smart contract templates for escrow, payment channels, and more.",
    price: 7.99,
    currency: "XRP",
    category: "Code",
    image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=500&h=500&fit=crop",
    rating: 4.9,
    sales: 2100,
    seller: "rpVh7YjJTokEm5GSAVbSP6JSCVH1XKuDxN",
  },
  {
    id: "4",
    name: "Market Analysis Report",
    description: "In-depth crypto market analysis 2024 with predictions and investment strategies.",
    price: 3.99,
    currency: "XRP",
    category: "Reports",
    image: "https://images.unsplash.com/photo-1460925895917-aeb19be489c7?w=500&h=500&fit=crop",
    rating: 4.5,
    sales: 650,
    seller: "rpVh7YjJTokEm5GSAVbSP6JSCVH1XKuDxN",
  },
  {
    id: "5",
    name: "API Integration Kit",
    description: "Ready-to-use API for DeFi platforms with complete documentation and examples.",
    price: 8.99,
    currency: "XRP",
    category: "API",
    image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=500&h=500&fit=crop",
    rating: 4.7,
    sales: 540,
    seller: "rpVh7YjJTokEm5GSAVbSP6JSCVH1XKuDxN",
  },
  {
    id: "6",
    name: "Security Audit Toolkit",
    description: "Comprehensive smart contract audit tools with automated vulnerability detection.",
    price: 9.49,
    currency: "XRP",
    category: "Security",
    image: "https://images.unsplash.com/photo-1563986768609-322d6d2fd4da?w=500&h=500&fit=crop",
    rating: 5.0,
    sales: 320,
    seller: "rpVh7YjJTokEm5GSAVbSP6JSCVH1XKuDxN",
  },
];
